#!/bin/bash

function mdk () {
    cd  ~/.wine-softoken/drive_c/Program\ Files/Secure\ Computing/SofToken-II/
    export WINEPREFIX=~/.wine-softoken
    PASSWORD=4815926
    USERID=fbicknel
    DES=$(wine Console_UI.exe $USERID <<<$PASSWORD | tail -1 | cut -c30-37)
}

OTP="/tmp/1timepw.$LOGNAME"
CONF=/etc/vpnc/default.conf
mdk
echo "Xauth password $DES" > $OTP
sudo /usr/sbin/vpnc-connect $CONF $OTP
/bin/rm $OTP
